export class AdminService {
  login() {}
  searchUsers() {}
  getUserDetail() {}
  suspendUser() {}
  restoreUser() {}
  listModerationReviews() {}
  decideModerationReview() {}
  purgeDocument() {}
  listReports() {}
  resolveReport() {}
  listSupportRequests() {}
  getSupportRequestDetail() {}
  replyToSupportRequest() {}
  updateSupportRequest() {}
  listAccountDeletionRequests() {}
  getAccountDeletionRequestDetail() {}
  approveAccountDeletionRequest() {}
  rejectAccountDeletionRequest() {}
  cancelAccountDeletionRequest() {}
  listLegalDocumentVersions() {}
  createLegalDocumentVersion() {}
  getLegalDocumentVersion() {}
  updateLegalDocumentVersion() {}
  publishLegalDocumentVersion() {}
  archiveLegalDocumentVersion() {}
  listNotices() {}
  createNotice() {}
  getNotice() {}
  updateNotice() {}
  publishNotice() {}
  archiveNotice() {}
  listFaqs() {}
  createFaq() {}
  getFaq() {}
  updateFaq() {}
  publishFaq() {}
  archiveFaq() {}
  getHomepageContent() {}
  updateHomepageContent() {}
  publishHomepageContent() {}
  getOverviewStats() {}
}
