export class AdminController {
  readonly routes = [
    'POST /v1/admin/auth/login',
    'GET /v1/admin/users',
    'GET /v1/admin/users/:userId',
    'POST /v1/admin/users/:userId/suspend',
    'POST /v1/admin/users/:userId/restore',
    'GET /v1/admin/moderation/reviews',
    'POST /v1/admin/moderation/reviews/:reviewId/approve',
    'POST /v1/admin/moderation/reviews/:reviewId/reject',
    'POST /v1/admin/moderation/documents/:documentId/purge',
    'GET /v1/admin/reports',
    'POST /v1/admin/reports/:reportId/resolve',
    'GET /v1/admin/support/requests',
    'GET /v1/admin/support/requests/:requestId',
    'POST /v1/admin/support/requests/:requestId/reply',
    'PATCH /v1/admin/support/requests/:requestId',
    'GET /v1/admin/account-deletion-requests',
    'GET /v1/admin/account-deletion-requests/:requestId',
    'POST /v1/admin/account-deletion-requests/:requestId/approve',
    'POST /v1/admin/account-deletion-requests/:requestId/reject',
    'POST /v1/admin/account-deletion-requests/:requestId/cancel',
    'GET /v1/admin/content/legal-documents',
    'POST /v1/admin/content/legal-documents',
    'GET /v1/admin/content/legal-documents/:documentId',
    'PATCH /v1/admin/content/legal-documents/:documentId',
    'POST /v1/admin/content/legal-documents/:documentId/publish',
    'POST /v1/admin/content/legal-documents/:documentId/archive',
    'GET /v1/admin/content/notices',
    'POST /v1/admin/content/notices',
    'GET /v1/admin/content/notices/:noticeId',
    'PATCH /v1/admin/content/notices/:noticeId',
    'POST /v1/admin/content/notices/:noticeId/publish',
    'POST /v1/admin/content/notices/:noticeId/archive',
    'GET /v1/admin/content/faqs',
    'POST /v1/admin/content/faqs',
    'GET /v1/admin/content/faqs/:faqId',
    'PATCH /v1/admin/content/faqs/:faqId',
    'POST /v1/admin/content/faqs/:faqId/publish',
    'POST /v1/admin/content/faqs/:faqId/archive',
    'GET /v1/admin/content/homepage',
    'PATCH /v1/admin/content/homepage',
    'POST /v1/admin/content/homepage/publish',
    'GET /v1/admin/stats/overview'
  ];
}
